import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author alexa
 */

public class StudProfilePage extends javax.swing.JInternalFrame {

    /**
     * Creates new form StudProfilePage
     */
    private int studentId;
   public StudProfilePage(int studentId) {
    this.studentId = studentId;
    initComponents();
    loadProfileImage();
    loadStudentInfo();

    this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
    ui.setNorthPane(null);
}

    
    private void loadProfileImage() {
    try {
        Connection conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/scholartrack_db", "root", "12345");
        String sql = "SELECT profile_pic FROM students WHERE student_id = ?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
       pstmt.setInt(1, studentId);

        ResultSet rs = pstmt.executeQuery();
        if (rs.next()) {
            byte[] imgBytes = rs.getBytes("profile_pic");
            if (imgBytes != null) {
                ImageIcon icon = new ImageIcon(new ImageIcon(imgBytes).getImage()
    .getScaledInstance(150, 150, Image.SCALE_SMOOTH));
      lblProfilePic.setIcon(icon);
            }
        }

        rs.close();
        pstmt.close();
        conn.close();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error loading profile image: " + ex.getMessage());
    }
}
    
    private void loadStudentInfo() {
    try {
        Connection conn = java.sql.DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/scholartrack_db", "root", "12345");

        String sql = "SELECT name, address, school, email, password FROM students WHERE student_id = ?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setInt(1, studentId);// Replace 1 with the actual logged-in student ID

        ResultSet rs = pstmt.executeQuery();
        if (rs.next()) {
            StudName.setText(rs.getString("name"));
            addressField.setText(rs.getString("address"));
            schoolcombo.setSelectedItem(rs.getString("school"));
            emailField.setText(rs.getString("email"));
            PasswordFieldNew.setText(rs.getString("password"));
            confirmPasswordField.setText(rs.getString("password"));
        }

        rs.close();
        pstmt.close();
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading student info: " + e.getMessage());
    }
}
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        StudName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblProfilePic = new javax.swing.JLabel();
        schoolcombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        PasswordFieldNew = new javax.swing.JPasswordField();
        confirmPasswordField = new javax.swing.JPasswordField();
        btnUploadPic = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 730));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 80, 20));

        StudName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel2.add(StudName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 340, 50));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("School:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        addressField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel2.add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 340, 50));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Address:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Email:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, -1));

        emailField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel2.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 370, 50));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("New Password");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Confirm Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProfilePic.setBackground(new java.awt.Color(204, 204, 204));
        lblProfilePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lblProfilePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 160));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 180, 160));

        schoolcombo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        schoolcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select your School", "School of Agriculture Sciences", "School of Aquatic Sciences", "School of Arts and Sciences", "School of Education ", "School of Engineering", "School of Engineering School of Industrial Technology", "School of Forestry and Environmental Sciences", "School of Information Technology", "College of Law" }));
        jPanel2.add(schoolcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 340, 50));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 80, -1));

        PasswordFieldNew.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel2.add(PasswordFieldNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 370, 50));

        confirmPasswordField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel2.add(confirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 370, 50));

        btnUploadPic.setBackground(new java.awt.Color(255, 255, 0));
        btnUploadPic.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUploadPic.setText("Upload");
        btnUploadPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPicActionPerformed(evt);
            }
        });
        jPanel2.add(btnUploadPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 90, 30));

        jPanel4.setBackground(new java.awt.Color(153, 153, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexa\\Downloads\\icons8-test-account-40.png")); // NOI18N
        jLabel8.setText("Profile");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 2, -1, 60));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 980, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPicActionPerformed
         JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Select Profile Picture");
    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

    int result = chooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();
        try {
            // Display in GUI
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(file.getAbsolutePath()).getImage()
                    .getScaledInstance(150, 150, Image.SCALE_SMOOTH));
            lblProfilePic.setIcon(imageIcon);

            // Store in DB
            FileInputStream fis = new FileInputStream(file);
            Connection conn = java.sql.DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/scholartrack_db", "root", "12345");

            String sql = "UPDATE students SET profile_pic = ? WHERE student_id = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
pstmt.setBinaryStream(1, fis, (int) file.length()); // parameter 1 = image
pstmt.setInt(2, studentId);  

            int rows = pstmt.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(null, "Profile picture saved to database!");
            }

            // Close resources after successful use
            pstmt.close();
            conn.close();
            fis.close();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Failed to load image: " + ex.getMessage());
        }
    }
    
    }//GEN-LAST:event_btnUploadPicActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // Show confirmation dialog before update
    int confirmed = JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to update your profile?", 
        "Confirm Update", 
        JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
        String name = StudName.getText();
        String address = addressField.getText();
        String school = schoolcombo.getSelectedItem().toString();
        String email = emailField.getText();
        String password = new String(PasswordFieldNew.getPassword());
        String confirmPassword = new String(confirmPasswordField.getPassword());

        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match!");
            return;
        }

        if (name.isEmpty() || address.isEmpty() || school.equals("Please select your School") || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill out all required fields.");
            return;
        }

        try {
            Connection conn = java.sql.DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/scholartrack_db", "root", "12345");

            String sql = "UPDATE students SET name = ?, address = ?, school = ?, email = ?, password = ? WHERE student_id = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, name);
            pstmt.setString(2, address);
            pstmt.setString(3, school);
            pstmt.setString(4, email);
            pstmt.setString(5, password);
            pstmt.setInt(6, studentId);

            int rows = pstmt.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Profile updated successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "No changes made.");
            }

            pstmt.close();
            conn.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error updating profile: " + ex.getMessage());
        }
    } else {
        // Optional: user canceled the update
        JOptionPane.showMessageDialog(this, "Profile update cancelled.");
    }


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordFieldNew;
    private javax.swing.JTextField StudName;
    private javax.swing.JTextField addressField;
    private javax.swing.JButton btnUploadPic;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblProfilePic;
    private javax.swing.JComboBox<String> schoolcombo;
    // End of variables declaration//GEN-END:variables
}
