import UserSession.UserSession;
import com.mysql.cj.Session;
import java.awt.Color;
import java.awt.Image;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

    
/**
 *
 * @author alexa
 */
public class StudentDashboard extends javax.swing.JFrame {
     
    /**
     * Creates new form StudentDashboard
     */
     Color DefaultColor,ClickedColor;
      private int studentId;
    private int loggedInStudentId;
     
  public StudentDashboard(int studentId) {
     this.loggedInStudentId = studentId; // Set it first
    initComponents();
    loadProfileImage(); // Now this uses the correct ID
    DefaultColor = new Color(255, 234, 0);
    ClickedColor = new Color(255, 255, 255);
    setLocationRelativeTo(null);

    StudDashPanel.setBackground(DefaultColor);
    StudScholarshipPanel.setBackground(DefaultColor);
    StudApplicationPanel.setBackground(DefaultColor);
    StudProfilePanel.setBackground(DefaultColor);

    jLabel9.setText("Good Day, " + getStudentName(loggedInStudentId) + "!");
}
   
      private void loadProfileImage() {
  try {
        Connection conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/scholartrack_db", "root", "12345");
        String sql = "SELECT profile_pic FROM students WHERE student_id = ?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
       pstmt.setInt(1, loggedInStudentId);
       
        ResultSet rs = pstmt.executeQuery();
        if (rs.next()) {
            byte[] imgBytes = rs.getBytes("profile_pic");
            if (imgBytes != null) {
                ImageIcon icon = new ImageIcon(new ImageIcon(imgBytes).getImage()
    .getScaledInstance(150, 150, Image.SCALE_SMOOTH));
      lblProfilePic.setIcon(icon);
            }
        }

        rs.close();
        pstmt.close();
        conn.close();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error loading profile image: " + ex.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        StudDashPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        StudScholarshipPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        StudApplicationPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        StudProfilePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rSButtonHover1 = new rojerusan.RSButtonHover();
        jPanel3 = new javax.swing.JPanel();
        lblProfilePic = new javax.swing.JLabel();
        jDesktopPaneStud = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 234, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudDashPanel.setBackground(new java.awt.Color(255, 234, 0));
        StudDashPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudDashPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StudDashPanelMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dashboard");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexa\\Downloads\\icons8-dashboard-40.png")); // NOI18N

        javax.swing.GroupLayout StudDashPanelLayout = new javax.swing.GroupLayout(StudDashPanel);
        StudDashPanel.setLayout(StudDashPanelLayout);
        StudDashPanelLayout.setHorizontalGroup(
            StudDashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudDashPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        StudDashPanelLayout.setVerticalGroup(
            StudDashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudDashPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(StudDashPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(StudDashPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 270, 60));

        StudScholarshipPanel.setBackground(new java.awt.Color(255, 234, 0));
        StudScholarshipPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudScholarshipPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StudScholarshipPanelMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Scholarships");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexa\\Downloads\\icons8-scholarship-40.png")); // NOI18N

        javax.swing.GroupLayout StudScholarshipPanelLayout = new javax.swing.GroupLayout(StudScholarshipPanel);
        StudScholarshipPanel.setLayout(StudScholarshipPanelLayout);
        StudScholarshipPanelLayout.setHorizontalGroup(
            StudScholarshipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudScholarshipPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        StudScholarshipPanelLayout.setVerticalGroup(
            StudScholarshipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudScholarshipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(StudScholarshipPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(StudScholarshipPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 270, 60));

        StudApplicationPanel.setBackground(new java.awt.Color(255, 234, 0));
        StudApplicationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudApplicationPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StudApplicationPanelMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Applications");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexa\\Downloads\\icons8-applications-40.png")); // NOI18N

        javax.swing.GroupLayout StudApplicationPanelLayout = new javax.swing.GroupLayout(StudApplicationPanel);
        StudApplicationPanel.setLayout(StudApplicationPanelLayout);
        StudApplicationPanelLayout.setHorizontalGroup(
            StudApplicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudApplicationPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        StudApplicationPanelLayout.setVerticalGroup(
            StudApplicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudApplicationPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(StudApplicationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(StudApplicationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 270, 60));

        StudProfilePanel.setBackground(new java.awt.Color(255, 234, 0));
        StudProfilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudProfilePanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StudProfilePanelMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Profile");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexa\\Downloads\\icons8-test-account-40.png")); // NOI18N

        javax.swing.GroupLayout StudProfilePanelLayout = new javax.swing.GroupLayout(StudProfilePanel);
        StudProfilePanel.setLayout(StudProfilePanelLayout);
        StudProfilePanelLayout.setHorizontalGroup(
            StudProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudProfilePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addGap(33, 33, 33)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        StudProfilePanelLayout.setVerticalGroup(
            StudProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StudProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(StudProfilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 270, 60));

        rSButtonHover1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rSButtonHover1.setText("Logout");
        rSButtonHover1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rSButtonHover1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonHover1MouseClicked(evt);
            }
        });
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 90, 30));

        jPanel3.setBackground(new java.awt.Color(255, 234, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProfilePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lblProfilePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 160));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 150));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 730));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel9.setText("Good Day + Students Name!");

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexa\\Downloads\\Blue Illustration University Circle Brand Logo (6).png")); // NOI18N

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 65)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Welcome to");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 234, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ScholarTrack");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel10))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel9)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel13)))
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jDesktopPaneStud.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneStudLayout = new javax.swing.GroupLayout(jDesktopPaneStud);
        jDesktopPaneStud.setLayout(jDesktopPaneStudLayout);
        jDesktopPaneStudLayout.setHorizontalGroup(
            jDesktopPaneStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPaneStudLayout.setVerticalGroup(
            jDesktopPaneStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneStudLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jDesktopPaneStud, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1080, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private String getStudentName(int studentId) {
    String name = "";
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/scholartrack_db", "root", "12345");
        String query = "SELECT name FROM students WHERE student_id = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setInt(1, studentId);
        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            name = rs.getString("name");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error fetching name: " + e.getMessage());
    }
    return name;
}
    

    
    
    private void StudDashPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudDashPanelMousePressed
        StudDashPanel.setBackground(ClickedColor);
        StudScholarshipPanel.setBackground(DefaultColor);
        StudApplicationPanel.setBackground(DefaultColor);
        StudProfilePanel.setBackground(DefaultColor);
    }//GEN-LAST:event_StudDashPanelMousePressed

    private void StudScholarshipPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudScholarshipPanelMousePressed
        StudDashPanel.setBackground(DefaultColor);
        StudScholarshipPanel.setBackground(ClickedColor);
        StudApplicationPanel.setBackground(DefaultColor);
        StudProfilePanel.setBackground(DefaultColor);
    }//GEN-LAST:event_StudScholarshipPanelMousePressed

    private void StudApplicationPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudApplicationPanelMousePressed
        StudDashPanel.setBackground(DefaultColor);
        StudScholarshipPanel.setBackground(DefaultColor);
        StudApplicationPanel.setBackground(ClickedColor);
        StudProfilePanel.setBackground(DefaultColor);
    }//GEN-LAST:event_StudApplicationPanelMousePressed

    private void StudProfilePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudProfilePanelMousePressed
        StudDashPanel.setBackground(DefaultColor);
        StudScholarshipPanel.setBackground(DefaultColor);
        StudApplicationPanel.setBackground(DefaultColor);
        StudProfilePanel.setBackground(ClickedColor);
    }//GEN-LAST:event_StudProfilePanelMousePressed

    private void StudDashPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudDashPanelMouseClicked
        jDesktopPaneStud.removeAll();
    jDesktopPaneStud.repaint();

    StudDashPage studdashpage = new StudDashPage(String.valueOf(UserSession.getStudentId()));
    jDesktopPaneStud.add(studdashpage);
    studdashpage.setVisible(true);
    }//GEN-LAST:event_StudDashPanelMouseClicked

    private void StudScholarshipPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudScholarshipPanelMouseClicked
        StudScholarshipPage page = new StudScholarshipPage(loggedInStudentId); // Use your new constructor
    jDesktopPaneStud.removeAll();
    jDesktopPaneStud.add(page).setVisible(true);
    }//GEN-LAST:event_StudScholarshipPanelMouseClicked

    private void StudApplicationPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudApplicationPanelMouseClicked
       
        StudApplicationPage studapplicationpage = new StudApplicationPage();
jDesktopPaneStud.removeAll();
jDesktopPaneStud.add(studapplicationpage).setVisible(true);
    }//GEN-LAST:event_StudApplicationPanelMouseClicked

    private void StudProfilePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudProfilePanelMouseClicked
    StudProfilePage studProfilePage = new StudProfilePage(loggedInStudentId);
    jDesktopPaneStud.removeAll();
    jDesktopPaneStud.add(studProfilePage).setVisible(true);
    }//GEN-LAST:event_StudProfilePanelMouseClicked


    
    private void rSButtonHover1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonHover1MouseClicked
          int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
    if (choice == JOptionPane.YES_OPTION) {
        this.dispose();
        new StudentLoginForm().setVisible(true); // Replace with your login frame class
    }
    }//GEN-LAST:event_rSButtonHover1MouseClicked

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover1ActionPerformed


 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StudApplicationPanel;
    private javax.swing.JPanel StudDashPanel;
    private javax.swing.JPanel StudProfilePanel;
    private javax.swing.JPanel StudScholarshipPanel;
    private javax.swing.JDesktopPane jDesktopPaneStud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblProfilePic;
    private rojerusan.RSButtonHover rSButtonHover1;
    // End of variables declaration//GEN-END:variables
}
